# Need to run with this export:

# In plaintext mode, we use the internal domain because we terminate TLS at the Gateway
bootstrap.servers=kafka.int.127-0-0-1.nip.io:443
security.protocol=PLAINTEXT

schema.registry.url=http://schemaregistry.int.127-0-0-1.nip.io
key.converter.schema.registry.url=http://schemaregistry.int.127-0-0-1.nip.io
value.converter.schema.registry.url=http://schemaregistry.int.127-0-0-1.nip.io
