kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${CMF_SERVICE_ACCOUNT}
subjects:
- kind: ServiceAccount
  namespace: ${NAMESPACE}
  name: ${CMF_SERVICE_ACCOUNT}
roleRef:
  kind: ClusterRole
  name: ${CMF_SERVICE_ACCOUNT}
  apiGroup: rbac.authorization.k8s.io