---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: manual-admin
  namespace: ${NAMESPACE}
spec:
  principal:
    name: "/administrators"
    type: group
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: manual-admin-connect
  namespace: ${NAMESPACE}
spec:
  clustersScopeByIds:
    connectClusterId: confluent-demo.connect
  principal:
    name: "/administrators"
    type: group
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: manual-admin-sr
  namespace: ${NAMESPACE}
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_confluent-demo
  principal:
    name: "/administrators"
    type: group
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: manual-controlcenter
  namespace: ${NAMESPACE}
spec:
  principal:
    name: controlcenter
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: manual-controlcenter-connect
  namespace: ${NAMESPACE}
spec:
  clustersScopeByIds:
    connectClusterId: confluent-demo.connect
  principal:
    name: controlcenter
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: manual-controlcenter-sr
  namespace: ${NAMESPACE}
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_confluent-demo
  principal:
    name: controlcenter
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: manual-connect-sr
  namespace: ${NAMESPACE}
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_confluent-demo
  principal:
    name: connect
    type: user
  role: SystemAdmin
