---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: controlcenter
  namespace: ${NAMESPACE}
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: ${ENVOY_GATEWAY_NAMESPACE}
    sectionName: tls-passthrough
  hostnames:
  - "confluent.${BASE_EXTERNAL_TLS_DOMAIN}"  # The SNI hostname to look for
  rules:
  - backendRefs:
    - name: controlcenter-0-internal
      port: 9021  # The port on your pod where TLS is terminated
