---
# User: prod
# Specific FlinkEnvironment in CMF
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: flink-user-prod-developermanage-fe-production
  namespace: confluent-demo
spec:
  principal:
    # user 'prod', identified by UUID
    name: "6195f0e9-ca66-4081-af57-967c0ef3f427"
    type: user
  clustersScopeByIds:
    cmfId: CMF-id
  resourcePatterns:
    - patternType: LITERAL
      name: production
      resourceType: FlinkEnvironment
  role: DeveloperManage
