apiVersion: platform.confluent.io/v1beta1
kind: FlinkApplication
metadata:
  name: production-state-machine-example-bar
  namespace: confluent-demo
spec:
  flinkEnvironment: production
  image: confluentinc/cp-flink:1.19.3-cp1
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
    kubernetes.taskmanager.cpu.limit-factor: "10"
    kubernetes.jobmanager.cpu.limit-factor: "10"
  #   "metrics.reporter.prom.factory.class": "org.apache.flink.metrics.prometheus.PrometheusReporterFactory"
  #   "metrics.reporter.prom.port": "9249-9250"
  serviceAccount: flink
  jobManager:
    resource:
      memory: 1048m
      cpu: 100m
  taskManager:
    resource:
      memory: 1048m
      cpu: 100m
  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    state: running
    parallelism: 1
    upgradeMode: stateless
  cmfRestClassRef:
    name: default
    namespace: confluent-demo