apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-insecure
  namespace: ${KEYCLOAK_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: keycloak-insecure.${BASE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080