---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: elasticsearch-sink
  namespace: ${NAMESPACE}
spec:
  class: "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    name: elasticsearch-sink
    topics: WIKIPEDIABOT
    topic.index.map: "WIKIPEDIABOT:wikipediabot"
    connection.url: "http://elasticsearch:9200"
    type.name: "_doc"
    key.ignore: "true"
    # key.converter.schema.registry.url: "https://schemaregistry:8085"
    # value.converter: "io.confluent.connect.avro.AvroConverter"
    # value.converter.schema.registry.url: "https://schemaregistry:8085"
    # value.converter.schema.registry.ssl.truststore.location: "/etc/kafka/secrets/kafka.client.truststore.jks"
    schema.ignore: "true"
    # Serializer configuration should be inherited from the connect worker
