---
# User: dev
# All FlinkApplications in FlinkEnvironment development
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: flink-user-dev-clusteradmin-fe-dev
  namespace: confluent-demo
spec:
  principal:
    # user 'dev', identified by UUID
    name: "044fc917-68fe-4ba2-8217-305555be129c"
    type: user
  clustersScopeByIds:
    cmfId: CMF-id
    flinkEnvironmentId: development
  role: ClusterAdmin