--- # Kafka Brokers
# Listeners:
# 9071: INTERNAL (mTLS)
# 9092: EXTERNAL (SASL_SSL, OIDC) - exposed externally on port 443
# 9072: REPLICATION (MTLS)
# 9073: TOKEN (SASL_SSL, OAUTHBEARER w/ MDS)

apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: ${NAMESPACE}
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:${CONFLUENT_PLATFORM_VERSION}
    init: confluentinc/confluent-init-container:${CFK_INIT_CONTAINER_VERSION}
  dataVolumeCapacity: 5Gi
  listeners:
    # INTERNAL: 9071 (TLS)
    internal:
      tls:
        enabled: true
    # EXTERNAL: 9092 (TLS)
    external:
      externalAccess:
        type: staticForHostBasedRouting
        staticForHostBasedRouting:
          port: 443
          domain: ${BASE_DOMAIN}
          brokerPrefix: kafka-
      tls:
        enabled: true
    # REPLICATION: 9072 (TLS)
    replication:
      tls:
        enabled: true
  services:
    kafkaRest:
      tls:
        enabled: true
  metricReporter:
    enabled: false
  dependencies:
    kRaftController:
      controllerListener:
        tls:
          enabled: true
      clusterRef:
        name: kraft
    metricsClient:
      url: https://controlcenter.${NAMESPACE}.svc.cluster.local:9090
      tls:
        enabled: true
        secretRef: tls-controlcenter
    schemaRegistry:
      tls:
        enabled: true
        secretRef: tls-kraft
      url: https://schemaregistry.${NAMESPACE}.svc.cluster.local:8081
  tls:
    secretRef: tls-kafka
