
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:${CONFLUENT_PLATFORM_SR_VERSION}
    init: confluentinc/confluent-init-container:${CFK_INIT_CONTAINER_VERSION}
  tls:
    secretRef: tls-schemaregistry
  configOverrides:
    server:
      # Only works with 7.9 and below
      - "resource.extension.class=io.confluent.kafka.schemaregistry.rulehandler.RuleSetResourceExtension,io.confluent.dekregistry.DekRegistryResourceExtension"
  # Optimized for demo start time; do not use for production
  podTemplate:
    probe:
      readiness:
        initialDelaySeconds: 30
        failureThreshold: 30
      liveness:
        initialDelaySeconds: 30
        failureThreshold: 30
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.${NAMESPACE}.svc.cluster.local:9071
      tls:
        enabled: true